name: Workflow a

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: lets go
        shell: bash
        run: echo "i am workflow aaaaa"

      - name: trigger wow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
         owner: Moshizzl3
         repo: pba_1_semester
         github_token: ${{ secrets.GH_SECRET }}
         workflow_file_name: Workflow-b.yml
         wait_interval: 10
         trigger_workflow: true
         wait_workflow: true